export const todoTypes = {
    EDIT_TODO: "EDIT_TODO",

    DELETE_TODO: "DELETE_TODO",
    DELETE_TODO_S: "DELETE_TODO_SUCCESS",
    DELETE_TODO_F: "DELETE_TODO_FAIL",
    CHANGE_COMPLETE: "CHANGE_COMPLETE",


    GET_STATUS: "GET_STATUS",
    CLEAR_COMPLETED: "CLEAR_COMPLETED",

    FILTER_TODO: "FILTER_TODO",

    FETCH_S: "FETCH_SUCCESS",
    FETCH_F: "FETCH_FAIL"
}