export const todoTypes = {
    EDIT_TODO: "EDIT_TODO",
    DELETE_TODO: "DELETE_TODO",
    CHANGE_COMPLETE: "CHANGE_COMPLETE",
    CLICK_ALL: "CLICK_ALL",
    GET_STATUS: "GET_STATUS",
    CLEAR_COMPLETED: "CLEAR_COMPLETED",
    KEY_UP_ENTER: "KEY_UP_ENTER",
    FILTER_TODO: "FILTER_TODO"
}